# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Christopher Pence
email: chris@pencels.net
description: > # this means to ignore newlines until "baseurl:"
  Take a look friends!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pencels.github.io" # the base hostname & protocol for your site
nav:
  - txt: Resume
    href: /resume
  - txt: GitHub
    href: https://github.com/pencels
    external: true
  - txt: Posts
    href: /posts
collections:
  posts:
    permalink: /:collection/:year/:month/:day/:slug
plugins:
  - jekyll-archives
  - jekyll-redirect-from
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive
  permalinks:
    tag: "/posts/tagged/:name/"

# Build settings
markdown: kramdown
